apiVersion: apps/v1
kind: Deployment
metadata:
  name: defam-spring-boot-app
  labels:
    app: defam-spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defam-spring-boot-app
  template:
    metadata:
      labels:
        app: defam-spring-boot-app
    spec:
      containers:
      - name: defam-spring-boot-app
        image: sadaydz/defam-spring-springboot-app:latest  # Imagen de Docker Hub
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://host.docker.internal:3306/defam-sql"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "2474786"
---
apiVersion: v1
kind: Service
metadata:
  name: defam-spring-boot-service
spec:
  type: NodePort
  selector:
    app: defam-spring-boot-app
  ports:
    - protocol: TCP
      port: 8080         # Puerto interno expuesto por el contenedor
      targetPort: 8080   # Puerto al que redirige dentro del contenedor
      nodePort: 30007    # Puerto accesible desde fuera del clúster
