version: "3.8"

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Puerto externo:interno de nuestra app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/defam-sql
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2474786
